import React, { useMemo } from 'react';

interface AIInsightsModalProps {
    insights: string;
    onClose: () => void;
}

const AIEnhancedIcon: React.FC<{className?: string}> = ({ className }) => (
    <svg xmlns="http://www.w3.org/2000/svg" className={className} viewBox="0 0 24 24" fill="currentColor">
        <path d="M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25zM12.5 8a.5.5 0 00-1 0v4.755a2.755 2.755 0 00-1.035.318.5.5 0 00-.43.894 3.755 3.755 0 001.965-.818V8zM12 18a1 1 0 100-2 1 1 0 000 2z"/>
        <path d="M11.625 5.625a.375.375 0 11.75 0 .375.375 0 01-.75 0zM7.125 7.875a.375.375 0 11.75 0 .375.375 0 01-.75 0zM16.125 7.875a.375.375 0 11.75 0 .375.375 0 01-.75 0z"/>
    </svg>
);


export const AIInsightsModal: React.FC<AIInsightsModalProps> = ({ insights, onClose }) => {
    
    const formattedInsights = useMemo(() => {
        return insights
            .replace(/\*\*(.*?)\*\*/g, '<strong class="font-semibold text-slate-800">$1</strong>')
            .replace(/\n/g, '<br />');
    }, [insights]);

    return (
        <div 
            className="fixed inset-0 bg-slate-900 bg-opacity-50 z-50 flex justify-center items-center"
            aria-modal="true"
            role="dialog"
            onClick={onClose}
        >
            <div 
                className="bg-sky-50 rounded-2xl shadow-2xl w-full max-w-2xl m-4 p-8 transform transition-all border border-amber-500/50"
                onClick={(e) => e.stopPropagation()}
            >
                <div className="flex justify-between items-start mb-6">
                    <div className="flex items-center gap-3">
                        <AIEnhancedIcon className="w-8 h-8 text-amber-600" />
                        <div>
                            <h2 className="text-2xl font-bold text-slate-800">AI Financial Insights</h2>
                            <p className="text-slate-500">Generated by Gemini</p>
                        </div>
                    </div>
                    <button onClick={onClose} className="text-slate-400 hover:text-slate-700 transition-colors p-1" aria-label="Close modal">
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>

                <div className="prose prose-slate max-w-none text-slate-600 bg-sky-100 p-6 rounded-lg border border-slate-200 max-h-[60vh] overflow-y-auto">
                   <div dangerouslySetInnerHTML={{ __html: formattedInsights }} />
                </div>

                <div className="flex justify-end gap-4 pt-6">
                    <button
                        type="button"
                        onClick={onClose}
                        className="w-full sm:w-auto bg-amber-600 text-white font-semibold px-6 py-3 rounded-lg hover:bg-amber-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-amber-500 transition-all shadow-md"
                    >
                        Close
                    </button>
                </div>
            </div>
        </div>
    );
};
